### ISSUE TITLE
Improve deployment performance

### ISSUE THREAD

**Issue by gregn610** [awslabs/aws-control-tower-customizations#12]
eg. deploying an S3 logging bucket to all accounts and all regions can take more than 30 mins. 
This makes adding new CF templates to the manifest (e.g. for CIS remediations) painful to develop and deploy.

**Comment by groverlalit** [comment]
Thanks for bringing this to our attention.
The deployment workflow uses underlying Stack Set settings to deploy stack instances. We recommend development of the template outside the solution pipeline for faster iteration. The deployment settings can be updated to higher fault tolerance for parallel deployments but not recommended to avoid parallel rollbacks in case of a failure.
Hope this helps.
