### ISSUE TITLE
Updating Control Tower UI with new Guardrails

### ISSUE THREAD

**Issue by charyeezy** [awslabs/aws-control-tower-customizations#13]
Hello, 

I was just wondering if these new SCPs and Config rules could appear as new Guardrails in the Control Tower console?

Cheers,

**Comment by cgswong** [comment]
@charyeezy Currently AWS Control Tower does not support custom guardrails so there is no integration with guardrails provided with AWS Control Tower and those external, such as those applied with this solution. Hence, external guardrails for the time being will not appear in the AWS Control Tower console. Custom guardrails is a roadmap item that the product team is pursuing.

**Comment by charyeezy** [comment]
Thank you for your response. I will be on the lookout.
