### ISSUE TITLE
Manifest version validation error

### ISSUE THREAD

**Issue by Maniarr** [awslabs/aws-control-tower-customizations#16]
Hello,

When i use the manifest version `2020-01-01` present in [documentation v1.1.0](https://s3.amazonaws.com/solutions-reference/customizations-for-aws-control-tower/latest/customizations-for-aws-control-tower-developer-guide.pdf) like:

```
---
region: <String>
version: 2020-01-01
...
```

CodeBuild failed to validate the manifest:

```
ERROR - validation.invalid
ERROR -  --- All found errors ---
ERROR - ["Enum '2020-01-01' does not exist. Path: '/version'"]
...
Phase complete: BUILD State: SUCCEEDED
```

The build succeeded, perhaps it should fail ?

In the [scripts archive](s3.amazonaws.com/solutions-reference/customizations-for-aws-control-tower/v1.1.0/custom-control-tower-scripts.zip) downloaded by the CodeBuild project, we only have the version for v1.0.0 available.

```
# validation/manifest.schema.yaml:6
  "version":
    type:      date
    required: True
    enum: [2019-12-01]
```

Can you update the specifications or modify the documentation to remove this error ?

**Comment by rakshb** [comment]
@Maniarr Hello. We have fixed this in our latest release of CFCT (V1.2)
