### ISSUE TITLE
resource already exists

### ISSUE THREAD

**Issue by fivehorizons** [awslabs/aws-control-tower-customizations#2]
Hello.  We have been using control tower and this customization tool since they both came out.    We have had issues with the templates failing on the 2nd run or when a new account is created.   It appears that the resource is not registering.  This may also be a template issue or completely a USER ERROR and for that I apologize wasting your time :)  .   Error below: 

The error message is the resource already exists

C Wong was on our account for a long time and introduced us to the tool when it was called Addon Framework.     

Extra question do you have AWS addons that can be shared?

**Comment by groverlalit** [comment]
Thanks for reaching our to us.
We recommend you to open a AWS support case to help you troubleshoot the error in the CloudFormation template.
In regards to Add-On, it is on our roadmap for the next release.

**Comment by cgswong** [comment]
@fivehorizons Has this been resolved? The 2nd run would likely fail as the template does not delete certain key resources which get created. Think of this is a precaution for some users making changes to the template (without appropriate guardrails) which may result in the resource, such as the Transit Gateway, getting replaced which would result in operational disruption. The new account creation is interesting, this this the spoke or the hub account?

**Comment by cgswong** [comment]
@fivehorizons Did this get resolved for you? The template used by solution does make non-unique names so it would have to be that those resources already exist with the name. Perhaps you can share the full row from the CFN output which would show the resource which already exists?
