### ISSUE TITLE
Deleting a stack

### ISSUE THREAD

**Issue by techish1** [awslabs/aws-control-tower-customizations#22]
Couldn't find a way to delete a stackset created using deploy_method: stack_set. Please advise

**Comment by techish1** [comment]
@georgebearden

**Comment by groverlalit** [comment]
Hello @techish1 
The solution supports deletion of stack instances if you delete an account name/id, OU name or region name from the manifest.yaml for a specific Stack Set resource . If you wish to the [delete stack set](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-delete.html) (including [deletion of all the stack instances](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stackinstances-delete.html#stackinstances-delete-console)), please use the Stack Set console. Also, please comment out or remove the Stack Set resource from the manifest.yaml to avoid recreation of the Stack Set in the next pipeline execution.
Hope this helps. Thanks for reaching out to us.

**Comment by techish1** [comment]
Thanks @groverlalit for clarification. 

I was expecting it would delete whole stacksetif I remove OU or the whole block of stack_set deployment from manifest file.
