### ISSUE TITLE
Retry Configuration should allow non-default options

### ISSUE THREAD

**Issue by sfblackl** [awslabs/aws-control-tower-customizations#23]
In /source/aws/utils/boto3_session.py, def get_client(self):
All 4 (boto3.client) calls should pass in config=Config structure and allow setting max number and retry as indicated here (https://boto3.amazonaws.com/v1/documentation/api/latest/guide/retries.html#defining-a-retry-configuration-in-a-config-object-for-your-boto3-client)

The reason for this is that currently list stack instances call will hit the default 4 retries frequently if there is a large number of stack instances (1K+).  Ideally AWS would increase the limits, but until then, it should be allowed to set overrides in some way.  Or if you can't set overrides, at least change to standard, 10 instead of legacy, 4.

**Comment by groverlalit** [comment]
Thanks for reaching out to us. We have added this request to our backlog.

**Comment by groverlalit** [comment]
Resolving. Shipped with release v2.1.
