### ISSUE TITLE
general question - manifest.yaml.j2 documentation and triggering the pipeline using s3

### ISSUE THREAD

**Issue by aksdari** [awslabs/aws-control-tower-customizations#27]
Hello Team, 

Nice work on this project!

I am working on some test scenarios for ControlTower and would like to use this project. However, I am having difficulties finding information about the following items: 

- `manfiest.yaml.j2` : 
any documentation related to this file available? should I have `manifest.yaml` and copy it into `manifest.yaml.j2` while changing only the region to a string interpolation?

- Triggering the pipeline on update:
When I update the package, upload it to s3 buckets, and then **update** cloudformation stack, the config deployer lambda does not update the S3 file that triggers the pipeline. any insights/docs on this would be appreciated. 

Thank you

**Comment by groverlalit** [comment]
@aksdari Thanks for reaching out.
1. manifest.yaml.j2 - This file exists in the repo to allow us to build manifest.yaml with the current region. [See code for details.](https://github.com/awslabs/aws-control-tower-customizations/blob/master/deployment/build-s3-dist.sh#L98-L108)
There is no reason to store this as j2 file in your repository/S3 bucket.

2. The config deployer lambda only updates the configuration file and stores it in user's choice of pipeline trigger. After the initial deployment, the custom configuration needs to be managed by the user directly updating the pipeline source trigger.
Hope this helps.

**Comment by aksdari** [comment]
Thank you for the clarification 👍
