### ISSUE TITLE
Versions of Solution in various forms

### ISSUE THREAD

**Issue by jwoods-ucsb** [awslabs/aws-control-tower-customizations#29]
Hello,

The Control Tower Customizations solution is offered from within Service Catalog as a Product as well as from the Solutions web site and github. 
The version number of the product on the [Solutions](https://aws.amazon.com/solutions/implementations/customizations-for-aws-control-tower/) page is 1.1
The latest version listed on github is 1.2
The version of the Service Catalog Product is 1.0

Is it possible to sync the releases so that all three are using the same version? If they are intentionally out of sync, could there be posted a release timing pattern?

Thanks

**Comment by groverlalit** [comment]
This is not an issue with the solution. We are looking into the workflow to avoid this confusion.
