### ISSUE TITLE
Deployment Errors

### ISSUE THREAD

**Issue by bfranzen1** [awslabs/aws-control-tower-customizations#3]
I ran into a couple of errors when initially deploying this AWS Solution. First, there seems to be a misconfiguration in the source stage of the codepipeline that is created. I had to add a "_" to the object name in this stage. Also, initially the account that the solution is deployed in has no access to download the customization templates from S3 because the KMS key used doesn't allow the root of the account to decrypt using the key.

**Comment by groverlalit** [comment]
Hello @bfranzen1,
The KMS key policy by default as a best practice doesn't add 'root' ARN to the policy. We recommend to add only needed user/group/role ARN to the key policy to limit the access to the resources encrypted by the solution KMS key.
Hope this helps.
Thanks
