### ISSUE TITLE
V1.2.0 CF validation ability to disable?

### ISSUE THREAD

**Issue by fivehorizons** [awslabs/aws-control-tower-customizations#30]
After Upgrading from 1.1 the first step S3 execution in code pipeline it fails on IAM policy but this is how we work and would like to disable the check?   ![image](https://user-images.githubusercontent.com/34970108/91230157-a1d74280-e6f0-11ea-918b-0a20e527d2db.jpeg)

**Comment by groverlalit** [comment]
@fivehorizons Thanks for reaching out. 
If you wish to ignore a specific warning or a failure, you can update the template in the configuration with metadata at the resource level. Please [see here for details].(https://github.com/awslabs/aws-control-tower-customizations/blob/master/deployment/custom-control-tower-initiation.template#L286-L294)
