### ISSUE TITLE
Build fails if OU has no accounts

### ISSUE THREAD

**Issue by aarondodd** [awslabs/aws-control-tower-customizations#37]
Manifest.yml uses "deploy_to_ou" and after kicking off the CodePipeline, if a listed OU has no accounts, build fails with:

`ValueError: The account list must have at least 1 valid account id. Please check the manifest under CloudFormation resource`

Fuller output from log:
```
{"time_stamp": "2020-10-07 17:37:39,390","log_level": "ERROR","log_message": Unhandled Exception: The account list must have at least 1 valid account id. Please check the manifest under CloudFormation resource: CcoeIamRoles. 
 Account List: [] 
 OU list: ['XXX']}
Traceback (most recent call last):
  File "state_machine_trigger.py", line 50, in main
    sm_input_list = get_stack_set_inputs()
  File "state_machine_trigger.py", line 78, in get_stack_set_inputs
    return get_stack_set_input.parse_stack_set_manifest()
  File "/codebuild/output/src406650435/src/manifest/manifest_parser.py", line 120, in parse_stack_set_manifest
    raise ValueError("The account list must have at least 1 "
ValueError: The account list must have at least 1 valid account id. Please check the manifest under CloudFormation resource: XXX. 
 Account List: [] 
 OU list: ['XXX']
Traceback (most recent call last):
  File "state_machine_trigger.py", line 102, in <module>
    main()
  File "state_machine_trigger.py", line 50, in main
    sm_input_list = get_stack_set_inputs()
  File "state_machine_trigger.py", line 78, in get_stack_set_inputs
    return get_stack_set_input.parse_stack_set_manifest()
  File "/codebuild/output/src406650435/src/manifest/manifest_parser.py", line 120, in parse_stack_set_manifest
    raise ValueError("The account list must have at least 1 "
ValueError: The account list must have at least 1 valid account id. Please check the manifest under CloudFormation resource: XXX. 
 Account List: [] 
 OU list: ['XXX']
```

Manifest_parser.py or such should have logic to handle a null account list for empty OUs.

**Comment by groverlalit** [comment]
@aarondodd This is an exception raised by the code to avoid triggering state machine execution (make Stack Set API call with an empty list). It seems like only account in the OU for this resource is the organizations master account. If that is a correct assumption, can you please retry after adding another account to the OU or update the OU name? Thanks.

**Comment by aarondodd** [comment]
> 
> @aarondodd This is an exception raised by the code to avoid triggering state machine execution (make Stack Set API call with an empty list). It seems like only account in the OU for this resource is the organizations master account. If that is a correct assumption, can you please retry after adding another account to the OU or update the OU name? Thanks.

There were no accounts in the OU I created and listed in the manifest.yml (I created "testou" and listed it in the manifest, but did not vend any accounts under it yet and did not move any accounts into it).

After creating an account in "testou" the error went away.

**Comment by trevorlatson** [comment]
ReOpen... Deploying to an empty OU is a common use case and we are having to work around this by specifying a dummy account just to get the pipeline to succeed...
