### ISSUE TITLE
pip '--use-feature=2020-resolver' errors in build scripts

### ISSUE THREAD

**Issue by mcripps9** [awslabs/aws-control-tower-customizations#39]
Not sure if this is really an issue or not, but every time pip is run in the build scripts (install_stage_dependencies.sh, etc.) it throws this "error" (which is really more of a warning):

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

The scripts run to completion, but since it is nearly the end of October 2020, we just want to make sure the solution won't break come next month.

**Comment by groverlalit** [comment]
@mcripps9 Thanks for reaching out to us. We validated the packages using the flag above before releasing v1.2.1.

**Comment by mcripps9** [comment]
Excellent!  I will close the issue then.  Thx!
