### ISSUE TITLE
Errors when updating a stack when previous deployment has failed

### ISSUE THREAD

**Issue by mcripps9** [awslabs/aws-control-tower-customizations#4]
After successfully deploying the solution, I made some changes to our template for the Audit account, redeployed, and it failed on the stack in our second region due to a dependency error.  So, I fixed it and redeployed, but now the code build fails.  I traced it down to the compare_template_and_params() function in sm_execution_manager.py.  At line 156 it does a "return operation_status_flag" to indicate the template needs to be re-deployed, but the function is supposed to return *two* parameters, so it fails with a "ERROR","log_message": Unhandled Exception: cannot unpack non-iterable bool object}" at line 54 where it calls the compare_template_and_params() function.  I think it needs to "return operation_status_flag, False".  A similar situation also exists on line 176 for a different error.

**Comment by groverlalit** [comment]
Thanks for opening the the pull request. We have added this to our backlog.

**Comment by rakshb** [comment]
@mcripps9 Hello! we have fixed this in CFCT V1.2
