### ISSUE TITLE
Control Tower Pipeline Testing Strategy

### ISSUE THREAD

**Issue by sasiki-coder** [awslabs/aws-control-tower-customizations#40]
Hi All,

I would like to test the individual add-on changes in a test aws account rather than going through checks for all the existing add-ons in a manifest.yaml file. Currently for each minor change, we'll have to wait for whole pipeline to run which takes about ~2 hrs which is time consuming

Also, how can we have separate pipeline  only for testing isolated from the production pipeline ? Currently we've a single pipeline being used for both the development and production code which resides in s3 bucket.

Any suggestions highly appreciated.

Thanks in advance
Sasi

**Comment by sasiki-coder** [comment]
Please let us know if additional information needed, thanks

**Comment by groverlalit** [comment]
Hello @sasiki-coder Thanks for reaching out to us. Can you please elaborate the first use case? Are you testing the templates in the add-on? Or wish to test the add-on manifest artifacts?
For the templates in the add-on, we recommend you to use stack set console to deploy the stack instances.
If you are testing add-on, the validation (build) stage should be able to catch any json/yaml/schema issues. 

With respect to separate pipeline for testing, development and production, is your preference to use same org master account or does separate org master account per environment works? Please advise. Thanks in advance.

**Comment by sasiki-coder** [comment]
Its the add-ons testing. Ideally we want to see speed up the testing process currently its taking ~1 hr to test the changes.

Also I see the pipeline execution is sequential not parallel, is there configuration that can be specified in manifest.yaml or somewhere to make it parallel execution ?

My current preference is to use same org master account, would want to isolate from development to production for testing any changes. 

Thanks

**Comment by groverlalit** [comment]
@sasiki-coder The current release does not support any setting that can change the sequential stack set deployment to parallel to avoid any issues if there is a dependency between stack sets.
