### ISSUE TITLE
Running cfn_nag_scan on unused template/parameter files

### ISSUE THREAD

**Issue by mikkelramlov** [awslabs/aws-control-tower-customizations#46]
I am trying to debug why the cfn_nag_scan exits with status 1, even though all scans returns:
```
Failures count: 0
Warnings count: 0
```

The easiest way to debug which stack is invalid should be to out comment the cloudformation_resources stacks in manifest file that might fail and then narrow it down. BUT even though you out comment the stacks in manifest file, the validation still runs on unused template and parameter files. This seems unessesary. 

Would it be possible to make cfn_nag more smart in what files it scans?

**Comment by groverlalit** [comment]
Hello @mikkelramlov, 
The code is [finding](https://github.com/awslabs/aws-control-tower-customizations/blob/master/source/validation/run-validation.sh#L113) the files in the template directory. Not reading the paths in the manifest file unless the f[ile path is a S3 URL.](https://github.com/awslabs/aws-control-tower-customizations/blob/master/source/validation/run-validation.sh#L48-L51). If you wish to skip the template file in the cfn_nag scan you coul move the file to a different folder (eg. toBeReviewed) in the configuration. Thanks
