### ISSUE TITLE
Error uploading configuration package to S3

### ISSUE THREAD

**Issue by jaglade** [awslabs/aws-control-tower-customizations#47]
Hi! I have been using custom control tower for a while now, but ever since i updated I am not allowed to copy the zip directly into the s3 bucket.  I have tracked it down to the bucket now uses a default encryption KMS key that is only allowing specific roles to use the key (It has been a while since i updated the custom control tower stack, sorry if im coming late with this issue).  I cant find in the documentation where I am doing something wrong, maybe someone can help?

Specific error on 's3 cp' is: 'An error occurred (AccessDenied) when calling the PutObject operation: Access Denied'

**Comment by groverlalit** [comment]
After you update the stack or deploy the stack - the KMS key policy is changed to default as defined in the CFN template. Please use document below to add new IAM user/role to allow use of the KMS key:
https://docs.aws.amazon.com/solutions/latest/customizations-for-aws-control-tower/appendix-a.html

**Comment by jaglade** [comment]
Yes, that worked.  I guess i was confused since it is a manual step, usually these customizations are automated.  Thanks!
