### ISSUE TITLE
Documentation issue: sample code incorrectly uses "parameter_name" instead of "parameter_key"

### ISSUE THREAD

**Issue by jdaves-ucar** [awslabs/aws-control-tower-customizations#49]
In the March 2021 developer guide, all the example code for inline parameter usage incorrectly use "parameter_name" to reference the key, which triggers an error in the pipeline build process.  The syntax documentation properly refers to this as "parameter_key".

**Comment by groverlalit** [comment]
Thanks for bringing this our attention. We will update the guide with the "parameter_key" in the examples.

**Comment by groverlalit** [comment]
This change was released in v2.1.0
