### ISSUE TITLE
Manually Trigger Execution

### ISSUE THREAD

**Issue by trevorlatson** [awslabs/aws-control-tower-customizations#52]
Is there an easy way to manually invoke the stack instead of being triggered by a new account creation event? This would be useful for us as we have a need to standardize the cloudformation stacks in place across previously deployed accounts as well as newly deployed accounts.

**Comment by mcripps9** [comment]
You can trigger the CodePipeline manually by hitting the 'Release Change' button.

**Comment by trevorlatson** [comment]
Closing, execution can be done manually with release change button
