### ISSUE TITLE
Parameterize account ids in manifest

### ISSUE THREAD

**Issue by mcripps9** [awslabs/aws-control-tower-customizations#53]
We use the same customizations package in two different organizations.  We would like the ability to parameterize the account ids in the deployment_targets:/accounts: section of the manifest so that we can use the same manifest across both organizations (we have a couple of instances where an account needs to be referenced by name vs. OU).  Ideally, the values come from the SSM parameter store in the master account home region so it can be set-and-forget.

**Comment by praveenis** [comment]
Hi @mcripps9 , 

We can add this as an enhancement request to our backlog. We will update the ticket once the request is ready for release.

Thanks,
Praveen

**Comment by groverlalit** [comment]
You can achieve this today if the account names (arbitrary) are same in both organizations. You can use the account names in the manifest using the current version.
