### ISSUE TITLE
Create Cloudformation Stackset directly at the OU Level

### ISSUE THREAD

**Issue by codemaestros-dev** [awslabs/aws-control-tower-customizations#57]
So we are starting to use this awesome project (thank you so much for putting this together) and really liking it so far, but I do have one question, wouldn't it be better if the stacksets were created directly as "Deploy to Organizational Unit" instead of doing what the manifest parser seems to be doing here: https://github.com/awslabs/aws-control-tower-customizations/blob/master/source/manifest/manifest_parser.py#L198 which is to build a list of accounts from the provided OU name. 

Apologies, if this is a stupid question, but I think it would be great if there was some documentation around why the OU feature for cloudformation stacksets is not being used.

**Comment by groverlalit** [comment]
Thanks @codemaestros-dev for sharing your feedback. The solution currently only supports self-managed stack sets that only supports 'Accounts' property.
The ability to deploy at the OU level is only supported for service-managed stack sets via DeploymentTargets property.
API Reference: [Link](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/cloudformation.html#CloudFormation.Client.create_stack_instances)

**Comment by faraazkhan** [comment]
This is interesting to me as well, we have a pretty large number of accounts and lots of stacksets, so our builds are very time consuming, would it be possible to at least expose `MaxConcurrentCount` or `MaxConcurrentPercentage` as a parameter somewhere so we are able to tune it to our needs?
