### ISSUE TITLE
Manifest version validation error 

### ISSUE THREAD

**Issue by senthil-nathan** [awslabs/aws-control-tower-customizations#58]
When i use the manifest version 2021-03-15 present in [documentation](https://s3.amazonaws.com/solutions-reference/customizations-for-aws-control-tower/latest/customizations-for-aws-control-tower-developer-guide.pdf) like:

---
region: ap-southeast-2
version: 2021-03-15
...
CodeBuild failed to validate the manifest:

ERROR - validation.invalid
ERROR -  --- All found errors ---
 ERROR - ["Enum '2021-03-15' does not exist. Path: '/version' Enum: [datetime.date(2020, 1, 1)]", "Key 'resources' was not defined. Path: ''"]
...

this shouldnt fail?

**Comment by groverlalit** [comment]
@senthil-nathan The error shows that 'resources' property is not in the manifest. Have you updated the properties supported in version 2021-03-15. Please see Appendix B in the [developer guide](https://s3.amazonaws.com/solutions-reference/customizations-for-aws-control-tower/latest/customizations-for-aws-control-tower-developer-guide.pdf) for details.

**Comment by groverlalit** [comment]
Closing this for now, please reopen if you continue to experience this issue.
