### ISSUE TITLE
manifest.yml version validation is fragile

### ISSUE THREAD

**Issue by dkewley-uci** [awslabs/aws-control-tower-customizations#59]
The code in v2.0.0 `validation/run-validation.sh` that validates the manifest.yml schema version is fragile, and prone to reporting `ERROR: Invalid manifest schema version.` in conditions that it should be able to accept.

This validation only succeeds if the following conditions hold:
* this line is the only line in the file containing the string 'version'
* this line has exactly two words, in one of the following forms (e.g. without a valid YAML comment postpended):
  * version: 2020-01-01
  * version: 2021-03-15

**Comment by tomjmarch** [comment]
+1. I hit this error when trying to deploy the "s3-versioning-enabled" config rule. Because it contains the string "version" it would fail validation.

**Comment by groverlalit** [comment]
Thanks for raising this concern. This is already on our backlog and we plan to ship the fix in the next release.

**Comment by groverlalit** [comment]
This change was released in v2.1.0.
