### ISSUE TITLE
Add CloudFormation Parameter to Opt Out of Collection of Operational Metrics

### ISSUE THREAD

**Issue by andywick-aws** [awslabs/aws-control-tower-customizations#62]
**Is your feature request related to a problem? Please describe.**

Most customers will not know that the collection of metrics setting is enabled by default. Customers should be able to opt out before any metrics are captured.

**Describe the feature you'd like**

Add a parameter to the initialization template that allows customers to opt out during the initial deployment of the solution.

**Additional context**
Instructions for opting out of the metrics collection: 
https://docs.aws.amazon.com/solutions/latest/customizations-for-aws-control-tower/appendix-b.html

**Comment by groverlalit** [comment]
Hi. In effort to minimize the parameters for the stack, this was kept as mapping that can be easily modified by the user.
