### ISSUE TITLE
Multiple pipelines

### ISSUE THREAD

**Issue by 0xjjoyy** [awslabs/aws-control-tower-customizations#63]
**Is your feature request related to a problem? Please describe.**

Would like to have multiple customizations pipeline so can separate out the deployments so one deployment doesn't block all. For example, a SCP that fails to deploy shouldn't block all other items that need to deploy, in the case of a single pipeline.

So far, I see that Custom-Control-Tower-CodePipeline is hardcoded in the policy and pipeline name.

**Describe the feature you'd like**

Ability to create multiple customizations pipeline and provide names to define the different pipelines.

**Additional context**

**Comment by groverlalit** [comment]
Hi @0xjjoyy. Thanks for the feature request. We don't plan to support it at this time.
