### ISSUE TITLE
Failure Tolerance not respected in StackSet execution resulting in entire pipeline failing

### ISSUE THREAD

**Issue by gtseamus** [awslabs/aws-control-tower-customizations#69]
**Is your feature request related to a problem? Please describe.**

It appears that the failure tolerance is not respected in the StackSets execution.

**Describe the feature you'd like**

I would like when I set the failure tolerance in the Customizations template to actually have an effect on individual StackSets execution instead I have to manually remediate any errors or else the entire build fails.  This results in a delay of 20 minutes or more depending on how many config rules/scps etc exist for the pipeline to evaluate.

Failure tolerance is set in the template and I have validated it at least runs when there are no issues cleanly and the parameters are showing up properly in the StackSet.

**Comment by groverlalit** [comment]
Hello @gtseamus To confirm the feature request is to set the fault tolerance at the stackSet level. Even with this feature the pipeline stage would fail if one of the stack Set operation fails. 

Do you intended to increase the fault tolerance for one of the StackSet to allow StackSet operation to succeed even though a large number of stack instances deployments will fail?

Can you please elaborate your use case? Thanks in advance.

**Comment by groverlalit** [comment]
Please feel free to reopen this issue if needed with use case(s) requested above. Thanks.
