### ISSUE TITLE
Log messages don't detail which stack/account/region caused the error

### ISSUE THREAD

**Issue by gregn610** [awslabs/aws-control-tower-customizations#7]
When a stackset bugs out there's no easy way to see which stack/ account / region caused the issue.

> Executing: CloudFormation/describe_stack_set_operation  

> "time_stamp": "2020-04-22 12:40:44,287","log_level": "INFO","log_message": { "StackSetName": "CustomControlTower-s3-access-logging-bucket", "TemplateURL": "https://s3.amazonaws.com/controltowercustomisatio-customcontroltower ...

> {"time_stamp": "2020-04-22 12:40:44,698","log_level": "INFO","log_message": { "StackSetOperation": { "OperationId": "c5410449-d03f-404d-8bba-f56c84db88be", "StackSetId": "CustomControlT

> {"time_stamp": "2020-04-22 12:40:44,698","log_level": "INFO","log_message": Operation Status: FAILED}

**Comment by groverlalit** [comment]
Thanks for reaching out to us. We will consider this feature in our next release. 
In the interim the details for the failure can be easily found in the State Machine execution details. Here are the steps to navigate the details:

1. Navigate to the AWS Step Functions console.
2. Click on the failed execution.
3. 
    a. If the error was due to Stack Set operation failure. You can click on the 'Send Failed Pass' stage and expand the 'Output' section to see the details for all regions. 
    b. If the error was due to an exception, you can click on the failed state and expand the 'Exception' section to see the details.
4. You can also navigate to AWS CloudFormation console (StackSets tab) to navigate to the Stack Set in question. The stack instances tab can help identify region/account level details.
