### ISSUE TITLE
Stepfunction not detecting changes to nested stacks

### ISSUE THREAD

**Issue by yogiwiz** [awslabs/aws-control-tower-customizations#70]
**Describe the bug**

We had our initial implementation using 1.2 of control tower customisations and moved to 2.1 recently. We use cloud formation nested stacks to deploy specific things to target OUs and accounts. In our of recent update, we realised that step function is not picking up any changes to child stack in a nested stack. Looking through the customisation code, we realised this was due to an improvement introduced in 2.0 to optimise the flow by comparing cloudformation templates using filecmp [here](https://github.com/awslabs/aws-control-tower-customizations/blob/26c1a652bc0c1633483446c13b05c4dbc4a8e10c/source/manifest/sm_execution_manager.py#L200).

**To Reproduce**

Deploy a nested stack to a target OU or account using CT customisation flow. Introduce an update to one of the child stacks in the nested stack. As part of customisation execution, step functions will not detect the change and hence no stackset update will be triggered

**Expected behavior**

Updates should be detected by CT customisation step function and changes should be pushed using stackset updates

**Please complete the following information about the solution:**

- [X] Version: v2.1.0
- [X] Region: ap-southeast-2
- [X] Was the solution modified from the version published on this repository? - No
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [X] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
- [X] Were there any errors in the CloudWatch Logs? [How to enable debug mode?] - No (https://docs.aws.amazon.com/solutions/latest/amazon-cloudwatch-monitoring-framework/troubleshooting.html)

**Additional context**
If this issue is not getting prioritised, please update the documentation so that it is a known limitation with nested stacks and CT customisation

**Comment by groverlalit** [comment]
The support to analyze the nested stacks is not supported. The template (file or remote path) in the manifest is only file is compared with the deployed stack set template.

**Comment by yogiwiz** [comment]
@groverlalit Can we please have documentation updated to reflect this? Especially for teams who were using older version and upgrading to latest?

**Comment by groverlalit** [comment]
Hi @yogiwiz The code you referred to in ticket was shipped in v1.1. It has been always only comparing the templates (top-level) in the manifest and not the nested stacks. Thanks.
